version: '3.8'
services:
  postgres:
    image: 'postgres'
    container_name: postgres
    ports:
      - "5540:5432"
    volumes:
      - ./volumes/postgres/data:/var/lib/postgres/data
      - ./db/db-init-scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - APP_DB_USER=${APP_DB_USER}
      - APP_DB_PASS=${APP_DB_PASS}
      - APP_DB_NAME=${APP_DB_NAME}

  db-adminer:
    container_name: dbadminer
    image: adminer
    ports:
      - 9002:8080