version: '3.8'
services:
  postgres:
    image: 'postgres'
    container_name: postgres
    ports:
      - "5540:5432"
    volumes:
      - ./volumes/postgres/data:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=potgres
      - POSTGRES_PASSWORD=training#2023

  db-adminer:
    container_name: dbadminer
    image: adminer
    ports:
      - 9002:8080